name: thermoswitches-mlbio
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.11
  - cd-hit
  - blast
  - hmmer
  - infernal
  - ncbi-datasets-cli
  - pandas
  - biopython
  - mysql-connector-python
  - python-dotenv
  - imbalanced-learn
  - scikit-learn
  - scipy
  - psutil
  - viennarna
  - matplotlib
  - seaborn
  - pip:
    - nupack  # install from local nupack-4.1.0.1/package/*.whl if pip index unavailable
    - xgboost
