from typing import Any

__version__: str

def set_max_threads(threads: int) -> None: ...
def get_max_threads() -> int: ...

class Model:
    def __init__(self, **kwargs: Any) -> None: ...

class SetSpec:
    def __init__(self, **kwargs: Any) -> None: ...

class Strand:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Tube:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Complex:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def tube_analysis(*args: Any, **kwargs: Any) -> Any: ...
def complex_analysis(*args: Any, **kwargs: Any) -> Any: ...
