from typing import Any

__version__: str

class fold_compound:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def mfe(self) -> tuple[str, float]: ...
    def pf(self) -> Any: ...
    def bpp(self) -> Any: ...
    def mean_bp_distance(self) -> float: ...

def fold(sequence: str) -> tuple[str, float]: ...
def md(*args: Any, **kwargs: Any) -> Any: ...
def file_PS_rnaplot(
    sequence: str, structure: str, output_path: str, *args: Any, **kwargs: Any
) -> int: ...
def tree_edit_distance(a: Any, b: Any) -> float: ...
def expand_Full(structure: str) -> Any: ...
